name: Github metrics

on:
  # Run manually or on a scheduled trigger
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  generate:
    permissions: 
      contents: write  # Cho phép ghi vào repository
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      # Generate metrics.svg using lowlighter/metrics action
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg  # Tạo file metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kidtomboy
          template: classic

      # Create the 'output' folder and move metrics.svg into it
      - name: Move metrics.svg to the output folder
        run: |
          mkdir -p output  # Tạo thư mục output nếu chưa có
          mv metrics.svg output/metrics.svg  # Di chuyển metrics.svg vào thư mục output

      # Push the metrics.svg from the 'output' folder to the output branch
      - name: Push metrics.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Đẩy file vào nhánh 'output'
          build_dir: .  # Đẩy thư mục hiện tại (có chứa output/metrics.svg) lên nhánh output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
