name: Github snake 🐍

on:
  # 📅 Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" # ⏰ Run at every 24 hours

  # 🛠️ Allow manual workflow execution
  workflow_dispatch:

  # 🔄 Run on every push to the master branch
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write # 🔏 Grant repository content write permissions
    runs-on: ubuntu-latest # 🐧 Run on the latest Ubuntu environment
    timeout-minutes: 5 # ⏳ Set a maximum runtime of 5 minutes

    steps:
      # 🐍 Generate the GitHub contributions snake animation in SVG format
      - name: 🐍 Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }} # 👤 GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg # 📂 Output path for light mode
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark # 🌙 Dark mode

      # 🚀 Push the generated snake SVG to the output branch
      - name: 📤 Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0 # ⚙️ Use GitHub Pages action to push the file
        with:
          target_branch: output # 🔀 Destination branch for the file
          build_dir: dist # 📂 Build directory containing the SVG files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 🔑 GitHub authentication token
