name: Snake eat GitHub Contributions 🐍

on:
   # 📅 Run automatically on schedule or manually triggered
  schedule:
    - cron: "0 * * * *" # ⏰ Run at midnight every day
  
  # 🛠️ Allow manual workflow execution
  workflow_dispatch:
  
  # 🔄 Run on every push to the master branch
  push:
    branches:
    - master
  
jobs:
  generate:
    permissions: 
      contents: write # 🔐 Grant repository content write permissions
    runs-on: ubuntu-latest # 🐧 Run on the latest Ubuntu environment
    timeout-minutes: 5 # ⏳ Set a maximum runtime of 5 minutes
    
    steps:
      # 🔍 Generates a snake game from a GitHub user's contributions graph
      - name: 🐍 Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3 # ⚙️ Use the snake game generator
        with:
          github_user_name: ${{ github.repository_owner }} # 👤 Use repository owner as the GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg # 🌟 Light mode output
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark # 🌑 Dark mode output
          
      # 🚀 Push the generated snake animation to the 'output' branch
      - name: 📤 Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0 # ⚙️ Use GitHub Pages action
        with:
          target_branch: output # 🔀 Destination branch
          build_dir: dist # 📂 Build directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 🔐 GitHub authentication token
